/*
 * File: app/view/MyFormPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyFormPanel', {
    extend: 'Ext.form.Panel',

    config: {
        items: [
            {
                xtype: 'formpanel'
            },
            {
                xtype: 'fieldset',
                title: '입사지원서',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'name',
                        label: '이름',
                        name: 'name'
                    },
                    {
                        xtype: 'datepickerfield',
                        id: 'birthday',
                        label: 'Field',
                        placeHolder: 'mm/dd/yyyy',
                        dateFormat: 'Y/m/d',
                        picker: {
                            useTitles: true,
                            dayText: '일',
                            monthText: '월',
                            slotOrder: [
                                'year',
                                'month',
                                'day'
                            ],
                            yearText: '년'
                        }
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        Ext.Date.monthNames = ['1월','2월','3월','4월','5월','6월',
        '7월','8월','9월','10월','11월','12월'];
    }

});