/*
 * File: app/view/daumPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.daumPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'daumPanel',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'daumTb',
                title: '다움 리스트',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'backBtn',
                        ui: 'back',
                        text: '이전'
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'daumListPanel',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'textfield',
                                flex: 8,
                                id: 'searchTf',
                                label: ''
                            },
                            {
                                xtype: 'button',
                                flex: 2,
                                id: 'searchBtn',
                                text: '검색'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 9,
                        id: 'daumList',
                        itemTpl: [
                            '<div style="padding:2px;margin:2px;height:66px;">',
                            '    <div style="width:60px;height:60px;margin:2px;float:left;">',
                            '        <img src="{cover_s_url}" width="60px" height="60px"/>',
                            '    </div>',
                            '    <div style="width:190px;height:60px;margin:auto 2px;float:left;">',
                            '        {title}',
                            '    </div>',
                            '    <div style="width:20px;margin:auto 2px;padding-top:20px;float:right;height:60px;">',
                            '        <img src="resource/images/arrow.png" width="18px" height="18px"/>',
                            '    </div>',
                            '</div>'
                        ],
                        store: 'daumStore',
                        plugins: [
                            {
                                autoPaging: true,
                                type: 'listpaging'
                            },
                            {
                                refreshFn: function(plugin) {
                                    var queryMsg = Ext.getCmp('searchTf').getValue();
                                    if(!queryMsg){
                                        Ext.Msg.alert('경고', '아~쫌...입력하고 눌러!');
                                        return;
                                    }
                                    var store = Ext.getStore('daumStore');
                                    store.removeAll();
                                    store.load({

                                        scope : this,
                                        params : {
                                            q : queryMsg,
                                            apikey : 'DAUM_SEARCH_DEMO_APIKEY',
                                            output : 'json',
                                            result : 20,
                                            pageno : 1
                                        }
                                    });
                                },
                                type: 'pullrefresh'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'daumPreviewPanel',
                tpl: [
                    '<div style="float:left">',
                    '    <img src="{cover_l_url}"/>',
                    '</div>',
                    '<div>',
                    '    제목',
                    '    :{title}',
                    '</div>',
                    '<div>',
                    '    상세내용',
                    '    : {description}',
                    '</div>'
                ]
            }
        ]
    }

});