Ext.define('MyApp.store.Account',{
	extend:'Ext.data.Store',
	requires:[
	    'MyApp.model.Contact1'
	],
	
	config:{
		autoLoad:true,
		model:'MyApp.model.Contact1',
		storeId:'account',
		proxy:{
			type:'ajax',
			url:'account.json',
			reader:{
				type:'json',
				rootProperty:'datas'
			}
		},
		sorters:{
			property:'irum'
		}
	}
});